title: "Tyagi Core"
description: "Deep Technology, Cyber Intelligence & Innovation Hub."
author: "Himanshu Tyagi"
url: "https://tyagicore.gklearnstudy.in"
baseurl: ""
permalink: /:title
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag

include:
  - admin

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
