backend:
  name: git-gateway
  repo: HimanshuTyagiJi/tyagicore
  branch: main
  identity_url: "https://astounding-dasik-6c4834.netlify.app/.netlify/identity"
  gateway_url: "https://astounding-dasik-6c4834.netlify.app/.netlify/git"
  publish_mode: editorial_workflow # Approval system ke liye

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "My Articles"
    folder: "" # Root directory
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
