backend:
  name: github
  repo: HimanshuTyagiJi/tyagicore
  branch: main
  base_url: https://api.netlify.com # Ye sirf login handle karega
  auth_endpoint: auth
  publish_mode: editorial_workflow # Tera approval system active rahega
