backend:
  name: git-gateway
  repo: HimanshuTyagiJi/tyagicore
  branch: main
  publish_mode: editorial_workflow # Approval system on hai

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "My Articles"
    folder: "" # <--- Ab ye seedha root check karega
    extension: "md" # Sirf Markdown files dikhayega
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
